2024-12-06 19:53:54,528ERRORsearch-appItem Frank not found in the list. Error: 'Frank' is not in list
Traceback (most recent call last):
  File "C:\Users\jim\Desktop\python-cf6\chapter05\18_logging_app2.py", line 69, in search_item
    index = items.index(item_to_find)
ValueError: 'Frank' is not in list
